name: Build Flutter Web
on:
  push:
    branches:
      - flutter_source
    paths:
      - 'version'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      # 获取flutter源码
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v2

      # flutter环境
      # https://github.com/marketplace/actions/flutter-action
      - name: build
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
          channel: 'stable'

      # 执行命令行
      - run: flutter pub get
      - run: flutter build web --release
      - run: cp other/CNAME build/web/CNAME
      - run: cp other/README.md build/web/README.md

      # https://github.com/JamesIves/github-pages-deploy-action
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          branch: master
          folder: build/web