name: Flutter Web Build To Github Page
on:
  push:
    branches:
      - flutter_source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build
        uses: subosito/flutter-action@v1
        with:
          channel: '2.0.6'
      - run: flutter pub get
      - run: flutter build web --release

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build/web